name: Report a bug
description: Stumbled across a bug? report it here.
title: "[Bug] "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report a bug with Terrastorage!  
        Before submitting, please make sure to read the [Feedback & Support](https://github.com/TimVincii/Terrastorage/#feedback--support) section to understand response times and other important information.
  - type: textarea
    attributes:
      label: What happened?
      description: Make sure to write down important details.
      placeholder: Describe the issue you encountered...
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ## Versions
  - type: input
    attributes:
      label: Terrastorage Version
      description: What version of Terrastorage were you using?
      placeholder: e.g., 1.x.x
    validations:
      required: true
  - type: input
    attributes:
      label: Fabric API Version
      description: What version of Fabric API were you using?
      placeholder: e.g., 0.10x.x
    validations:
      required: true
  - type: dropdown
    attributes:
      label: Minecraft Version
      description: What version of Minecraft were you using?
      options:
        - "1.21.3"
        - "1.21.2"
        - "1.21.1"
        - "1.21"
        - "1.20.1"
        - "1.20"
        - "Other"
    validations:
      required: true
  - type: markdown
    attributes:
      value: |
        ## Additional Information
  - type: textarea
    attributes:
      label: Relevant Log Output
      description: Please copy and paste any relevant log output. This will be automatically formatted into code, so no need for backticks.
      placeholder: Relevant logs...
      render: shell
  - type: textarea
    attributes:
      label: Other Mods
      description: If you can, please supply a list of installed Mods (besides Terrastorage and Fabric API).
      placeholder: List other mods you have installed...
      render: shell
  - type: markdown
    attributes:
      value: |
        Thank you for helping me improve Terrastorage!